### ISSUE TITLE
[Comment] Tax & VATMOSS

### ISSUE THREAD

**Issue by Keiron-BWS** [laravel/spark#101]
I realise both of my comments are about the payment side of spark, but I think this is one of it's best features.

I'm looking at how sales tax can be charged, and in particular EU VATMOSS.

In the SparkServiceProvider I can't see a way that a normal sales tax could be charged?

Building on that, most applications that I suspect Spark would be used for are digital subscriptions which come under VATMOSS (until the EU decide on some kind of threshold at least), for the uninitiated VATMOSS means that if you have clients in the EU for digital products you should be charging them VAT at the rate of the client country (and collect two pieces of evidence that they live in that country).

I've built this without Spark by taking the client address and VAT number if applicable and then using the package ddeboer/vatin to validate the VAT number otherwise charging them VAT at the country they've given.

I believe that once the card is tokenized the card country is available, so this could potentially be the ideal time to calculate the tax percentage and pass it through before the subscription is created, but we also need to notify clients we're going to be charging them that tax.

I'd suggest any code for this would need to be in the SparkServiceProvider.php rather than overwriting anything in the vendor directory and I'm struggling to see how it might be achieved?

**Comment by mpociot** [comment]
You might want to take a look at this: https://github.com/laravel/spark/pull/97

**Comment by Keiron-BWS** [comment]
Thanks @mpociot just what I wanted!
