### ISSUE TITLE
Authorizable Interface not found in the User model after install

### ISSUE THREAD

**Issue by mattarnster** [laravel/spark#104]
Hi,

I've just installed spark on top of my existing Laravel 5.1 application. However, now when I go to the application, I have the following exception:

"Interface 'Illuminate\Contracts\Auth\Access\Authorizable' not found"

I'm unsure as to what went wrong here, as far as I can see inside the /vendor/laravel/framework/src/Illuminate/Contracts/Auth folder, there's no Access folder either.

Can anyone see what I'm doing wrong? Apologies if you need more info to help, I'll be happy to provide whatever you need.

Here's the includes & traits I have in my current User.php model.

```
namespace App;

use Illuminate\Auth\Authenticatable;
use Laravel\Cashier\Billable;
use Laravel\Spark\Teams\CanJoinTeams;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Laravel\Cashier\Contracts\Billable as BillableContract;
use Illuminate\Contracts\Auth\Access\Authorizable as AuthorizableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;
use Laravel\Spark\Auth\TwoFactor\Authenticatable as TwoFactorAuthenticatable;
use Laravel\Spark\Contracts\Auth\TwoFactor\Authenticatable as TwoFactorAuthenticatableContract;

class User extends Model implements AuthorizableContract,
                                    BillableContract,
                                    CanResetPasswordContract,
                                    TwoFactorAuthenticatableContract
{
    use AuthorizableContract, Billable, CanResetPassword, TwoFactorAuthenticatable;
```

**Comment by mpociot** [comment]
What version of laravel does your app use? Authorization was added in 5.1.11

**Comment by mattarnster** [comment]
Ah... php artisan --version output the following: Laravel Framework version 5.1.7 (LTS)

So, I just need to upgrade my Laravel Framework version then? Is there a standard process to follow?
