### ISSUE TITLE
Fails to install correctly if the app name has been changed

### ISSUE THREAD

**Issue by idmontie** [laravel/spark#131]
I get the following when error when trying to run `spark install`: 

```
PHP Fatal error:  Class 'App\Providers\AppServiceProvider' not found in /var/www/html/horsefly/vendor/laravel/framework/src/Illuminate/Foundation/ProviderRepository.php on line 146
```

Steps to reproduce:

```
composer create-project laravel/laravel --prefer-dist
php artisan app:name Horsefly
spark install
```

**Comment by idmontie** [comment]
I suppose the following should be expected, either:

1. It works with the app being renamed
2. It is documented that `spark install` should be run before changing the app:name

In either case, I was able to fix this manually by fixing any `App/` references that the spark installation added.

**Comment by peterquentin** [comment]
@idmontie I think it should be 2. because renaming app is part of crafting your application, and when you start supporting crafted apps then it'll start to add up pretty fast.
