### ISSUE TITLE
Translation to other languages

### ISSUE THREAD

**Issue by w00p** [laravel/spark#134]
Hi,
Where is the word "monthly" and "yearly" in the files? i Want to translate it to Norwegian.
Is it possible?

**Comment by mpociot** [comment]
Just publish the views and replace it.

https://github.com/laravel/spark/search?utf8=%E2%9C%93&q=yearly&type=Code
https://github.com/laravel/spark/search?utf8=%E2%9C%93&q=monthly&type=Code

**Comment by w00p** [comment]
Thank you, but none of the files you referenced changed the language "monthly" and "yearly" on the frontpage and under registration when choosing a plan.

**Comment by miggynascimento** [comment]
Not sure if this will help, but there's a really good laravel package for setting up translatable models.

https://github.com/dimsav/laravel-translatable

On Nov 22, 2015, at 4:16 PM, w00p <notifications@github.com<mailto:notifications@github.com>> wrote:


Thank you, but none of the files you referenced changed the language "monthly" and "yearly" on the frontpage and under registration when choosing a plan.

-

**Comment by w00p** [comment]
I found it :) Thax
