### ISSUE TITLE
Spark install error, copy create_subscriptions_tables, No such file or directory

### ISSUE THREAD

**Issue by joakoan** [laravel/spark#145]
I'm having this problem when I install spark, in a fresh installation of laravel 5.2

[ErrorException]                                                                                                                  
  copy(.../vendor/laravel/spark/resources/stubs/database/migrations/2014_10_12_100000_create_subscriptions_tables.php): failed to open stream: No such file or directory

**Comment by hvent90** [comment]
why was this closed? I have the same issue.

**Comment by chaseconey** [comment]
Same issue here

**Comment by joakoan** [comment]
I closed the problem because I found it was already reported, here https://github.com/laravel/spark/issues/142
