### ISSUE TITLE
Conflict with Parsedown

### ISSUE THREAD

**Issue by kayyyy** [laravel/spark#15]
I already had a markdown parser installed from `"graham-campbell/markdown"`.
Spark is using `"erusev/parsedown"` which will end in a conflict and my markdown views are not loaded anymore.

Do you really need this parser just for the terms of use?

**Comment by GrahamCampbell** [comment]
Why would they conflict? I'm not sure what you mean?

**Comment by GrahamCampbell** [comment]
What version of my markdown package are you using?

**Comment by kayyyy** [comment]
@GrahamCampbell I am using `"graham-campbell/markdown": "~4.0",` 
Since i installed spark the .md view is no longer loaded.

If i visit the page where the .md file is loaded i get 
`View [sites.tutorials.content] not found. (View: /home/vagrant/Code/hostianer-app/resources/views/sites/tutorials/show.blade.php)`

![image](https://cloud.githubusercontent.com/assets/8193345/9903565/9ea33a1e-5c77-11e5-99f7-bf95da6954b8.png)

**Comment by GrahamCampbell** [comment]
I can't see anywhere where spark registers anything with the view system?

**Comment by kayyyy** [comment]
It was only my thought that the two parser having a conflict because Spark also uses a markdown parser package.
And since i installed spark my .md views are not longer loaded.

**Comment by kayyyy** [comment]
If i now use the `erusev/parsedown` which is installed by spark it works with this package.

sites/tutorials/content.blade.php
```
<?php

$Parsedown = new Parsedown();

echo $Parsedown->text($tutorial->content);
```

**Comment by GrahamCampbell** [comment]
You shouldn't need to do that though.
