### ISSUE TITLE
Default role of team member is not set

### ISSUE THREAD

**Issue by kcalliauw** [laravel/spark#16]
User A and B, Team X
User A invites user B to Team X
User B accepts the invitation
User A navigates to the Team membership page

User A expects to see the team members, but instead gets an empty content panel. On the JS console, an error is logged:
Uncaught TypeError: Cannot read property 'text' of undefined (app.js:28914)

The filter that is applied to the role name cannot be applied since the value of 'role' is null.

**Comment by kcalliauw** [comment]
I mean the filter that is applied in spark\settings\team\tabs\membership.blade.php on line 91. Remove the filter and the page will display.

**Comment by kcalliauw** [comment]
This was part of a larger issue with Invitations actually. I have made a PR that seems to fix it:

https://github.com/kcalliauw/spark/commit/63b47de8f0fb264be3f8d0c2c1c7ab9d68f81223

**Comment by kcalliauw** [comment]
merged.

https://github.com/laravel/spark/commit/093871414ca1b4e74fa47164b7a25cb32973106d

**Comment by Sirlazer2** [comment]
This issue still happens to me.

When I join a team with an already created account, the default role is not applied, and I get this JS error.
