### ISSUE TITLE
Instructions for getting Spark to work with latest 5.2 release

### ISSUE THREAD

**Issue by owenconti** [laravel/spark#163]
This is not an issue, just helpful information for other users looking to update to 5.2 production release while using Spark.

Remove the Billable contract from your User model:
Remove line from User model: `use Laravel\Cashier\Contracts\Billable as BillableContract;`
Remove `BillableContract` from `implements` list in User model

~~I temporarily updated my config/auth.php to add back the removed `model` property, until Spark is updated to point at the new `providers` config property.~~

~~Add this line to config/auth.php:~~
~~`'model' => App\User::class,`~~

Taylor has already made the changes on the Spark side to support 5.2. Make sure you update your composer.json to get the latest Spark changes:

`"laravel/spark": "1.0.x-dev",`

**Comment by aaranmcguire** [comment]
Just looked into the laravel/cashier repo, the Billable trait is now name not in a folder so its referenced like `use Laravel\Cashier\Billable as BillableContract;` Does this work? (I don't have the setup to test it at the moment).

Also, it may be worth submitting this as a PR if it works, saying that I know @taylorotwell has some changes in a local branch so it may already be fixed in his branch.

**Comment by owenconti** [comment]
@aaranmcguire - No, that trait is already included, its the first 'use' line in User. It needs to stay just like it is. You only need to remove the `use Laravel\Cashier\Contracts\Billable as BillableContract;` line.

I'll check the repo and see if the changes are already in there.

**Comment by aaranmcguire** [comment]
@owenconti It looks like this change has already been made in master, https://github.com/laravel/spark/commit/3af73681a0a3d2aba6aa9d827f7b5f53a0d83ca2

**Comment by kjfdebruin** [comment]
With latest laravel dev installation installed using
`composer create-project laravel/laravel app dev-develop`
and spark dev installation installed using
`composer global require "laravel/spark-installer=dev-master"` followed by `spark install`
I get the following error
`[ErrorException] class_parents(): object or string expected`
Anyone here also having this problem?

**Comment by robertpcontreras** [comment]
Yep, had this problem a few days ago. Found a quick solution in #171

**Comment by kjfdebruin** [comment]
Thanks @robertpcontreras, that solved it for me.

**Comment by netors** [comment]
For me, this was happening at the usingTeams() method of the Laravel\Spark class, specifically this:

    CanJoinTeams::class, class_uses_recursive(config('auth.providers.users.model'))

so adding this line to the boot() method of my SparkServicePRovider did the trick for me:

    config(['auth.providers.users.model' => config('auth.model')]);

**Comment by morrislaptop** [comment]
Was the other way round - `config(['auth.model' => config('auth.providers.users.model')]);`
