### ISSUE TITLE
Dashboard Responding as if I'm Guest

### ISSUE THREAD

**Issue by JordanDalton** [laravel/spark#168]
After logging in with a valid user account I am redirected to the dashboard page. However, the dashboard and background ajax calls are acting as if I'm not logged in.

<img width="821" alt="screen shot 2015-12-28 at 3 00 24 pm" src="https://cloud.githubusercontent.com/assets/1389886/12025411/582d3d34-ad74-11e5-94d3-4d25743ecdc8.png">

I have confirmed that the session data shows I'm logged in at the user.

<img width="1237" alt="screen shot 2015-12-28 at 3 01 43 pm" src="https://cloud.githubusercontent.com/assets/1389886/12025419/67608c98-ad74-11e5-89c4-61d72e2cf723.png">

<img width="1236" alt="screen shot 2015-12-28 at 3 02 07 pm" src="https://cloud.githubusercontent.com/assets/1389886/12025554/acaa498c-ad75-11e5-8e62-de14038f7276.png">

**Comment by danjy** [comment]
It's an issue with logging into Spark - go check in your spark account to see if they've populated. If not, check your config credentials

**Comment by danjy** [comment]
I think it's an issue with Stripe - go check Stripe to see if that user has populated in their system. Had a similar issue and I had a type in my Stripe config credentials.

**Comment by JordanDalton** [comment]
The user is populated in Stripe.

**Comment by danjy** [comment]
Gotcha. Then prob the same prob identified in issue #167

**Comment by JordanDalton** [comment]
Thanks @danjy.
