### ISSUE TITLE
ErrorException when running spark install

### ISSUE THREAD

**Issue by robertpcontreras** [laravel/spark#171]
I get the following error when trying to run the installer. I am running this on a fresh installation of Laravel 5.2.

[ErrorException]                            
class_parents(): object or string expected

Thanks

**Comment by nickdenardis** [comment]
@robertpcontreras 
Try updating your global composer `~/.composer/composer.json` to point the spark-installer to `dev-master`. There are a handful of updates in master for 5.2.

```
{
    "require": {
        "laravel/installer": "~1.1",
        "laravel/spark-installer": "dev-master"
    }
}
```

There are also some instructions in #163 if you run into similar contact issues.

**Comment by robertpcontreras** [comment]
Ive found a solution. There is probably a better way but it works.

Change line 36 of the InstallCommand class in the spark-installer package to 

$process = new Process($composer . ' require laravel/spark:1.0.x-dev', null, null, null, null);

Previously spark install was automatically installing the v0.2.3 which wasnt working with 5.2
