### ISSUE TITLE
Password reset request results in "No hint path defined for [auth.spark]."

### ISSUE THREAD

**Issue by adamstamper** [laravel/spark#181]
On a clean 5.2 app, with newly installed Spark, the default 'password reset' email template in /config/auth.php [line 101] is set as `auth.spark::emails.auth.password.email`

As a result, when posting a password reset request (from "/password/email") an error is shown: "No hint path defined for [auth.spark]."

Instead the default 'password reset' email template in /config/auth.php should be:
`spark::emails.auth.password.email`

Thanks for all your work on Spark, can't wait to deploy my first app built on this.

**Comment by aaranmcguire** [comment]
You should create a PR if you have the fix. :)

**Comment by aaranmcguire** [comment]
... or do you want me to create a fix/PR?

**Comment by adamstamper** [comment]
@aaranmcguire Sorry took me a while to figure out the cause and post a fix, by which time you'd beaten me to it!!

**Comment by aaranmcguire** [comment]
@adamstamper Thats fine, I was going to hold off until I got a reply saying if you knew where the issue was but forgot it adds the message.
