### ISSUE TITLE
Cannot Delete Teams

### ISSUE THREAD

**Issue by jamstarter** [laravel/spark#190]
When I create a team, I only have a "Leave" button. It looks like there is supposed to be a delete button as well. When I click "Leave" the team disappears, but reloading the screen reveals that I have not left the team (assuming because I am the owner). I've checked to make sure I am set as the owner in the database and all looks good there.

![image](https://cloud.githubusercontent.com/assets/1464685/12219344/a175824c-b70d-11e5-9efd-53b4e0038f3d.png)

When looking at my network tab, a 500 error is thrown. 

![image](https://cloud.githubusercontent.com/assets/1464685/12219341/919a1fa4-b70d-11e5-8d27-68433b751162.png)

Am I missing something or is this a bug?

**Comment by maisnamraju** [comment]
Have you set up the roles in your Provider file, something like 

 protected function customizeRoles()
    {
        Spark::defaultRole('admin');

        Spark::roles([          
            'admin' => 'Administrator',
            'manager' => 'Manager',
            'team' => 'Member',
        ]);
    }

**Comment by jamstarter** [comment]
thanks! I'll give it a shot!
