### ISSUE TITLE
Any timeline for Beta?

### ISSUE THREAD

**Issue by andrewfreddin** [laravel/spark#192]
I have been eagerly awaiting "Laravel Spark" after its introduction at Laracon last year. In the introductory keynote/video, Otwell said to expect a beta in September. However, when I look at the readme.md, the software is still in alpha several months later. Has the readme.md file simply been overlooked or is something seriously impeding the progress of this software? Is the Laravel Spark platform stable enough to start developing on now?

I am not trying  to rush anything and I apologize if this question comes off that way, I am just trying to clarify. 

Thanks in advance.

**Comment by KHucks** [comment]
@andrewfreddin I was in the exact same situation. See Taylor's comment on this topic in #152

**Comment by andrewfreddin** [comment]
Thanks for that!

For anyone else who sees this issue and is wondering the same thing, here is the comment:
"It will probably be done in the next few months. I plan to use it on my own projects so it has to be at a level I'm comfortable using for my own stuff, which is a fairly high standard :smile: "
