### ISSUE TITLE
.env file not found on new install

### ISSUE THREAD

**Issue by afolson** [laravel/spark#25]
Followed the directions in README but received the following error on `spark install`:

[ErrorException]
  file_get_contents(/Users/amanda/sparky/.env): failed to open stream: No such file or directory

`touch .env` before `spark install` results in the following error:
  
[ErrorException]
  mkdir(): File exists

The docs seem to imply that you don't need to create an `.env` file before installing Spark. Running the installer in debug mode (note: it gets angry if you run the install, it barfs, and you try to run it again as it seems to create migrations every time) doesn't provide any useful output. Happy to help troubleshoot/get a PR in if you tell me how you want to deal with it (either via code or via updating docs).

Additional crap:
Running PHP 5.6.11 (cli) (built: Aug  4 2015 16:19:18)
OSX 10.10.5
Composer version 1.0-dev (7267b2ed9063ef64e7dda86421a928a802558fdb) 2015-09-14 14:48:45
Composer lock file: https://gist.github.com/afolson/31e56295980e0c858ee9

**Comment by kayyyy** [comment]
You dont have to install the `.env` file because before you install spark you have to install laravel which comes already with the `.env` file.

**Comment by kylestev** [comment]
@kayyyy Laravel doesn't create a `.env` file, rather, it comes with a `.env.example` file. Typically, you simply run `$ cp .env.example .env` before running your app to get things working. You are right that you should be running this in a Laravel-like project, though. :smile:

**Comment by afolson** [comment]
Yeah the issue is that the docs don't say you need to configure Laravel-specific stuff before running the command to install Spark things. If you create the `.env` file after `laravel new site` but before running `spark install` it still gets mad because the file exists (presumably something is trying to create one and not expecting one to exist?)

**Comment by kayyyy** [comment]
If you create a new laravel app the .env file is copied automaticly
`Created project in laravel-test
> php -r "copy('.env.example', '.env');"`

**Comment by afolson** [comment]
This is happening on a fresh install -- not a previous app.

If you look at the composer.json file I linked, it's pulling in laravel/framework and not laravel/laravel. That's what Laravel's CLI installer is giving me when I create a new project.

**Comment by kayyyy** [comment]
As i said - If you are using spark on an existing app you get some trouble. Not only with the `.env` file also with the `gulp` compilation etc.

So for now i would suggest to install spark on a fresh install not on an existing app.

**Comment by afolson** [comment]
Again, this is a brand new app that I have created, not an existing app.

**Comment by ryanwohara** [comment]
@kayyyy rif.org - No need to be pedantic about things you didn't read :)

@afolson Are all your composer packages fully updated? After using `laravel new application' I have an .env file (and .env.example)

**Comment by Cyruxx** [comment]
The problem here is that after running laravel new app, the composer post-install is running through which already copies the .env.example file to .env and then when you run spark install it tries to redo that step, causing a error because the file already exists.

Am I right? :-)

**Comment by sgrover** [comment]
I installed via the composer command `composer create-project laravel/laravel myapp -prefer-dist` - this method automatically creates the .env and sets the application key.  Would this clear up the issue you are seeing?  Or is there a reason I shouldn't be doing the create-project method that I'm not aware of yet?
