### ISSUE TITLE
Some subscriptions plans do not render on the home page.

### ISSUE THREAD

**Issue by sgrover** [laravel/spark#31]
I'm trying out the subscription plans, following the details in the readme.  I've added 3 plans to my Stripe account, and uncommented the FREE plan.  When viewing the home page, only the free plan and the first Stripe plan render.  Dumping the $plans variable on the welcome.blade.php view shows only two plans in the list.

Here's my customizeSubscriptionPlans() method (and I hope I didn't make a noob typo somewhere...):
```
protected function customizeSubscriptionPlans()
    {
        Spark::free()
                ->features([
                    'Feature 1',
                    'Feature 2',
                    'Feature 3',
                ]);

        // Spark::plan('Basic', 'stripe-id')->price(10)
        //         ->trialDays(7)
        //         ->features([
        //             'Feature 1',
        //             'Feature 2',
        //             'Feature 3',
        //         ]);
                

        Spark::plan('Testing', 'test3')->price(9.99)
                ->trialDays(10)
                ->yearly()
                ->features([
                    'Testing 1',
                    '2 Testing',
                    'Testing 3',
                ]);
        
        Spark::plan('Agency', 'agency-monthly')->price(299.99)
                ->trialDays(30)
                ->features([
                    'Agency 1',
                    '2 Agency',
                    'Agency 3',
                ]);

        Spark::plan('Agency2', 'agency-yearly')->price(2999.99)
                ->trialDays(30)
                ->yearly()
                ->features([
                    'Year',
                    '2 Agency',
                    'Agency 3',
                ]);                
    }
```
Only the Free and "Agency" plan appears.

**Comment by benmag** [comment]
I was able to replicate this issue

Seems to be caused by `->yearly()`. Removing `->yearly()` makes all the plans show correctly.

**Comment by sgrover** [comment]
I noticed the plans show properly on the /register page though when toggling between monthly/yearly.  The welcome page is "simple pricing".  I'm looking through the code now to find where that $plans variable is populated, but my Laravel-foo may not be up to this task (yet).

**Comment by sgrover** [comment]
Ahh. at line 188 of the welcome.blade.php:
```
<?php $plans = Spark::plans()->monthly()->active(); ?>
```
So the "simple pricing" only shows monthly plans. K.  That's straight forward, I guess.  It's left to us to customize that view as needed then.
