### ISSUE TITLE
Bitcoin Payment

### ISSUE THREAD

**Issue by kayyyy** [laravel/spark#35]
Since Stripe offers the ability to pay also with bitcoin it would be awesome if spark would support also the payments with bitcoin.

**Comment by phroggyy** [comment]
Is Bitcoin not just another currency. A much broader, and just as easy, implementation is adding support to specify the currency to be used on a plan.

**Comment by kayyyy** [comment]
Not really. If you want to pay with Bitcoin you have to enable this in stripe. It`s a diffrent payment then € / USD.

https://stripe.com/docs/guides/bitcoin

**Comment by phroggyy** [comment]
Well, you can't do that though. https://support.stripe.com/questions/can-i-pay-subscriptions-in-bitcoin-with-stripe

**Comment by kayyyy** [comment]
@phroggyy Ah .. thank you for the link. Thats a pity :(
