### ISSUE TITLE
Incorrect validation on update password

### ISSUE THREAD

**Issue by bgurney** [laravel/spark#37]
Hey, loving Spark so far. Not a big issue but just spotted that the default password validation is set to max:6 instead of min:6 in app/Http/Controllers/Settings/SecurityController.php:52

I think most people will just override this in the app/Providers/SparkServiceProvider but thought I'd mention it.

**Comment by kayyyy** [comment]
pull #38

**Comment by bgurney** [comment]
Thanks for that kayyyy :-)
