### ISSUE TITLE
Gulp fails to compile

### ISSUE THREAD

**Issue by kayyyy** [laravel/spark#4]
Gulp tries to find the `app.js` which isnt there
```
gulp-notify: [Laravel Elixir] Browserify Failed!: Cannot find module '/Users/chris/Desktop/code/hostianer-app/chris/assets/js/app.js' from '/Users/chris/Desktop/code/hostianer-app'
{ [Error: Cannot find module '/Users/chris/Desktop/code/hostianer-app/resources/assets/js/app.js' from '/Users/chris/Desktop/code/hostianer-app']
```

![image](https://cloud.githubusercontent.com/assets/8193345/9862566/030d36c4-5b3a-11e5-84a2-1877e227ae6e.png)

**Comment by taylorotwell** [comment]
So the file was not properly copied in your resources/assets/js? Was this a new app or an existing app?

**Comment by kayyyy** [comment]
seems so - but the app.js is also not in the git repo. maybe it should be the spark.js ?
it was an existing app - after a bit of testing i will now install a fresh app with spark.

just thought you need some issue reports :)

**Comment by kayyyy** [comment]
Ok just installed a fresh app - the welcome page is now working. but the app.js is not compiled. still getting the issue

![image](https://cloud.githubusercontent.com/assets/8193345/9863609/e145e3b2-5b41-11e5-912e-412d98b937ed.png)

**Comment by kayyyy** [comment]
Okay - just installed a fresh app. Now it seems to work.
Is it currently not possible to integrate spark within an existing app? :)
