### ISSUE TITLE
CSS Stylesheet not included: spark-app/public/css/app.css missing

### ISSUE THREAD

**Issue by fishmad** [laravel/spark#43]
Is it just me or is the stylesheets not included in these laravel downloads?

Hosted view - display incorrect
![capturecss](https://cloud.githubusercontent.com/assets/12012101/9931687/407c12b6-5d81-11e5-9ca9-4495fc7ad82f.PNG)

Source view points to css/app.css
![capturecsssource](https://cloud.githubusercontent.com/assets/12012101/9931688/43b1446a-5d81-11e5-98c4-c9c40bb7616a.PNG)

css/app.css not in fresh download/installation
![capturefolder](https://cloud.githubusercontent.com/assets/12012101/9931691/4690188c-5d81-11e5-9dac-b1f6b04f8b04.PNG)

**Comment by GrahamCampbell** [comment]
Probably because you forgot to run gulp...

**Comment by fishmad** [comment]
ohhh maybe your right - I didn't know that. I've never had much luck getting GULP it to work.
![capturegulp](https://cloud.githubusercontent.com/assets/12012101/9931775/00e0aaee-5d82-11e5-84a4-057e3c33ee1c.PNG)

**Comment by GrahamCampbell** [comment]
Looks like you forgot to first run npm install.

**Comment by fishmad** [comment]
Thanks Graham looks like I forgot everything, I noticed node_modules folder already in my project root and  assumed it was all downloaded already - guess not; I've just deleted node_modules and running clean npm install again hopefully get a clean install for once...

and once again it doesn't download / install correctly - I cannot get to work, npm install doesn't like me.
![capturenpm-install](https://cloud.githubusercontent.com/assets/12012101/9932113/8f973576-5d84-11e5-8341-603724d3a706.PNG)

**Comment by GrahamCampbell** [comment]
Maybe try updating node?

**Comment by GrahamCampbell** [comment]
If it helps, I'm using windows, and v0.12.7 works fine for me.

**Comment by Cyruxx** [comment]
@fishmad As the error message says, try running this command as sudo.

**Comment by GrahamCampbell** [comment]
Oh, wait, I see you're using skydrive. That's probably what's breaking everything.

> As the error message says, try running this command as sudo.

On windows, really?

**Comment by Cyruxx** [comment]
@GrahamCampbell  Just updated my comment.

**Comment by GrahamCampbell** [comment]
That's still a bad idea. Don't do that.

**Comment by GrahamCampbell** [comment]
The issue lies with skydrive jumping in and locking stuff when npm wants to use it, which is why it';s saying that.

**Comment by fishmad** [comment]
I use in skydrive so I can work on app from home pc and work pc as its syncs all my work.

BTW:I had skydrive disabled as I was aware it was always touching files, my version of node is v4.XX
should I uninstall and try the older version - or try with sudo first as per Cyruxx and if that does not work I can relocate from skydrive then try again.

**Comment by jbrooksuk** [comment]
> I use in skydrive so I can work on app from home pc and work pc as its syncs all my work.

This is what Git is for.

**Comment by fishmad** [comment]
I cant install Git on work PC (Administrator permission required - unless a portable version exists) Skydrive comes pre installed.

**Comment by fishmad** [comment]
Steps as above helped me get this working now thanks
