### ISSUE TITLE
Question: how to define plan limitations / features?

### ISSUE THREAD

**Issue by kelvinj** [laravel/spark#48]
… but not using the features method, which is used for marketing.

I.e. Basecamp has:
- 10 Projects – `limitActiveProjects: 10`
- 40 Projects – `limitActiveProjects: 40`
- Annual unlimited – `limitActiveProjects: null`

If there's no way of doing this right now, but it's considered a useful addition, I'll knock a PR up.

**Comment by cwt137** [comment]
I think this is a duplicate of #39 and there is no way to do it right now.

**Comment by kelvinj** [comment]
Closing as similar to discussion in #39
