### ISSUE TITLE
[Question] Spark routes

### ISSUE THREAD

**Issue by oleynikd** [laravel/spark#62]
Hi,

First of all, thank you @taylorotwell for such a cool tools!!!

#### Question 1
I guess it's a stupid question however:
There are a lot of different routes used in Spark blade templates, like: `url('/password/email')`, `url('/login')`, `url('/logout')` ... But where are all those routes? 

#### Question 2
I'm building a service that will be used mostly on Mobile Apps. So I need the way to authenticate users via some API and sessions/cookies is not an option, I need to provide some kind of access token to mobile app after successful login for further requests. Is it possible using Spark? If not, how can I customize the login/logout API logic?

Thanks.

**Comment by BrainBuzzer** [comment]
Well first of all,

## Answer to your first Q

these all routes are setup in the routes file whose location in this project is here: 
[https://github.com/laravel/spark/blob/master/app/Http/routes.php](https://github.com/laravel/spark/blob/master/app/Http/routes.php)

Then,

# Answer 2:

> Why the hell would anyone do that with the help of laravel spark? 

I would definitely choose something like `dingo/api` for that kind of support. And maybe, you should teach it to yourself. ;-)

**Comment by eduardocruz** [comment]
@oleynikd You are probably looking for something like Json Web Tokens: 

- https://github.com/tymondesigns/jwt-auth
- http://www.toptal.com/web/cookie-free-authentication-with-json-web-tokens-an-example-in-laravel-and-angularjs

**Comment by oleynikd** [comment]
Thank you guys for fast responses. I'll investigate these...
