### ISSUE TITLE
ErrorException after installation

### ISSUE THREAD

**Issue by msieprawski** [laravel/spark#71]
After calling `spark install` script ends with error:
```
[ErrorException]                                                             
  file_get_contents(/path/to/htdocs/spark.dev/.env): fa  
  iled to open stream: No such file or directory  
```

**Comment by aaranmcguire** [comment]
Did you pull laravel from git? I've tried with Laravel new {Project} and it works, but cloning laravel/laravel and then doing the spark install gives the error.

**Comment by msieprawski** [comment]
Ahhh, I see - you are totally right. My mistake. I've installed spark first and then I've pulled laravel instance. After changing the order it works fine. Thanks!
