### ISSUE TITLE
events?

### ISSUE THREAD

**Issue by curkle** [laravel/spark#73]
This is not or maybe not a bug.

I am new to laravel, I saw laravel support events model and Spark has some events already. Tried myself and not working.

can anyone list the events and write an example how to add new listener.

Thanks.

**Comment by aaranmcguire** [comment]
It's a lot to put in a comment so take a look at these links..

http://laravel.com/docs/5.1/events#registering-events-and-listeners
http://laravel.com/docs/5.1/events#defining-listeners

**Comment by curkle** [comment]
Thanks. I have tried this but I just can't find add listener for vendor events. as my understanding i can't or should not add files to vendor folders

**Comment by aaranmcguire** [comment]
It may be worth prepopulating the app/Providers/EventServiceProvider.php file with spark as it's meant for new projects anyway..

@curkle Let me get back to you with an example on what ones to register and where.

**Comment by aaranmcguire** [comment]
This should be how your `app/Providers/EventServiceProvider.php` looks

```php
/**
 * The event listener mappings for the application.
 *
 * @var array
 */
protected $listen = [
    'App\Events\User\Registered' => [
        'App\Listeners\YourListenerClassHere',
    ],
    'App\Events\User\Subscribed' => [
        'App\Listeners\YourListenerClassHere2',
    ],
];
```

**Comment by curkle** [comment]
Thanks.  but  User Registred is already defined  at spark events. 

so should i change 
`'App\Events\User\Registered' => [
        'App\Listeners\YourListenerClassHere',
    ],
`to 
`
'Lavel\Spark\Events\User\Registered' => [
        'App\Listeners\YourListenerClassHere',
    ],
`

however second one looks not working at my side .

**Comment by aaranmcguire** [comment]
`Lavel\Spark\Events\User\Registered` to `Laravel\Spark\Events\User\Registered`

**Comment by curkle** [comment]
ok. Thanks. thanks. however they can list all the events for SPARK for reference. 

best regards. thanks by the way.

**Comment by aaranmcguire** [comment]
I'm sure this will come with the documentation.
