### ISSUE TITLE
Class 'Laravel\Spark\Providers\SparkServiceProvider' not found

### ISSUE THREAD

**Issue by krishnakanthpps** [laravel/spark#76]
Did a fresh install on a Amazon EC2 cloud for spark. Followed the instructions to install Laravel from here http://mnmtechconsulting.com/blog/setting-up-laravel-5-ubuntu-14-04-amazon-ec2#set-up-lamp-stack-on-ubuntu-ec2-instance and then followed steps to install spark from here https://mattstauffer.co/blog/introducing-laravel-spark-a-deep-dive

Still am getting this error 

PHP Fatal error:  Class 'Laravel\Spark\Providers\SparkServiceProvider' not found in /var/www/html/TestApp/bootstrap/cache/compiled.php on line 6843

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Laravel\Spark\Providers\SparkServiceProvider' not found

Any solution? 

Added sparkprovider class in the app.php file. But nothing helps.

**Comment by aaranmcguire** [comment]
have you tried dumping autoload?

`composer dump-autoload` & `php artisan clear-compiled`

**Comment by austinkregel** [comment]
I also had this issue. I solved this by making sure my installation of laravel, composer, node, and bower were all up to date. Once I made sure that they were up to date, had the proper permissions and the proper configuration,  I was able to create a new Laravel instance and issue the `spark install` command.

**Comment by aejnsn** [comment]
This sounds like a dump autoload problem, but I don't understand why you would have to dump autoload after the fact. The Spark-Installer requires the Spark package via Composer, and thus dumps autoload after installing the Spark package.

**Comment by krishnakanthpps** [comment]
Thank you @austinkregel Your advise worked. 

Created a new laravel app and installed laravel and then ran the spark install. and it worked well.

**Comment by austinkregel** [comment]
I'm glad it worked :D I hope you can build something wonderful :)
