### ISSUE TITLE
[Proposal] Creating Admin Panel

### ISSUE THREAD

**Issue by aaranmcguire** [laravel/spark#78]
Not sure if this is in scope for this project or if it should be created as a separate package, but I think it would be great if there was an admin panel for administering users/teams (at least for the basic stuff that comes out of the box with Spark).

It could allow site admins to modify user data without going into the DB or creating their own admin panel (and spark it meant to stop developers from creating the basics).

If this is a wanted feature I will write a proposal.

**Comment by karlmonson** [comment]
+1

**Comment by aejnsn** [comment]
@aaranmcguire Whether or not this becomes a part of Spark, I'd like to contribute to it.

**Comment by aaranmcguire** [comment]
@aejnsn Great, thank you.

**Comment by aaranmcguire** [comment]
@taylorotwell If this was created would the PR be accepted?

**Comment by taylorotwell** [comment]
Should be a separate package.

**Comment by aaranmcguire** [comment]
Cool, good to know.. Thanks.
