### ISSUE TITLE
validateRegistrationsWith Not overriding 

### ISSUE THREAD

**Issue by wwallace** [laravel/spark#96]
Looks like validateRegistrationsWith() in customizeRegistration() is not actually overriding the default rules.

**Comment by aaranmcguire** [comment]
Have you got a code snippet so I can test later today?

**Comment by mikhailkozlov** [comment]
It was fixed in https://github.com/laravel/spark/pull/66 @wwallace need to get dev-master / 1.0.x-dev

**Comment by wwallace** [comment]
Thanks @mikhailkozlov
