### ISSUE TITLE
[Comment] PCI-DSS with Stripe?

### ISSUE THREAD

**Issue by Keiron-BWS** [laravel/spark#98]
Does the Spark implementation of Stripe use one of the PCI-DSS compliant methods to make life even easier? 
https://support.stripe.com/questions/do-i-need-to-be-pci-compliant-what-do-i-have-to-do

My reason for asking is that I know PCI-DSS is about 12 pages of pre-filled data if you use stripe.js or checkout (and therefore don't see the card), but it around 80 pages of compliance if you use something other.
Spark makes life so easy to create subscription based app, but I worry that many could fall foul of this if they don't realise and Spark doesn't use the easier compliance route.

**Comment by phroggyy** [comment]
@Keiron-BWS as long as you aren't storing any of the sensitive data, you're fine. In fact, stripe.js doesn't allow you to charge money from your users if you're not on HTTPS, so this isn't really much an issue of Spark.

**Comment by Keiron-BWS** [comment]
@phroggyy Both stripe.js and stripe checkout use an iframe so that you don't see the card data, you just get a token back in your form to pass through and charge against the token, but I think Spark is using the PHP SDK (rather than stripe.js or checkout) as I can't see an iframe? See links below:

https://support.stripe.com/questions/what-about-pci-dss-3-1
http://stackoverflow.com/questions/32725930/if-using-the-stripe-php-sdk-do-i-need-to-be-pci-compliant-still

I think the reason the iframe moves it outside of a more complicated compliance is that by accepting the card data in a POST (rather than just a token) you effectively are storing the data (RAM, log files etc).

**Comment by phroggyy** [comment]
Nope. Stripe.js does not use an iframe when used separately, that's only
Checkout, the card data never touches the server on Spark.
su 4. lokakuuta 2015 klo 20.31 Keiron-BWS <notifications@github.com>
kirjoitti:

**Comment by Keiron-BWS** [comment]
@phroggyy Aha, I've just run up a test install and can see it pulling in Stripe JS v2 from stripe.com - so are we saying it's definitely in the easier compliance route?

**Comment by phroggyy** [comment]
Yep. You can also see that it doesn't put name attributes on the fields, so they never pass the server. Actually, if you examine the source, you'll see that a JavaScript function to retrieve a stripe token is executed before submitting.

**Comment by Keiron-BWS** [comment]
Perfect... Closing this.
